/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.edu.untdf.catalogo.views;
import ar.edu.untdf.catalogo.CatalogoApp;
import ar.edu.untdf.catalogo.controller.CategoriaJpaController;
import ar.edu.untdf.catalogo.controller.exceptions.NonexistentEntityException;
import ar.edu.untdf.catalogo.jtablemodelo.CategoriaTableListener;
import ar.edu.untdf.catalogo.jtablemodelo.CategoriaTableModel;
import ar.edu.untdf.catalogo.jtablemodelo.ClienteTableModel;
import ar.edu.untdf.catalogo.modelo.Categoria;

import javax.persistence.Persistence;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import javax.swing.border.TitledBorder;
import java.awt.Rectangle;
import javax.swing.JLabel;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
/**
 *
 * @author Matias
 */
public class Categorias extends javax.swing.JInternalFrame {

	private CategoriaJpaController cat = new CategoriaJpaController(Persistence.createEntityManagerFactory("catalogo"));		

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form Categorias
     */
    public Categorias() {
		setRootPaneCheckingEnabled(false);
		setBorder(new TitledBorder(null, "", TitledBorder.LEADING, TitledBorder.TOP, null, null));
		//setSize(359,293);
		setTitle("Administracion de Categorias");
		setClosable(true);
        initComponents();
        CategoriaTableListener listener = new CategoriaTableListener(this);
        tableCategorias.getSelectionModel().addListSelectionListener(listener);
        
        
    }

    public JButton getAceptar() {
        return aceptar;
    }

    public void setAceptar(JButton aceptar) {
        this.aceptar = aceptar;
    }

    public JButton getCancelar() {
        return cancelar;
    }

    public void setCancelar(JButton cancelar) {
        this.cancelar = cancelar;
    }

    public JTextField getFieldApellido() {
        return fieldCuidad;
    }

    public void setFieldApellido(JTextField fieldApellido) {
        this.fieldCuidad = fieldApellido;
    }


    public JTable getTableCategorias() {
        return tableCategorias;
    }

    public void setTableCategorias(JTable tableCategorias) {
        this.tableCategorias = tableCategorias;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCategorias = new javax.swing.JTable();
        fieldCuidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nuevo = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        tableCategorias.setModel(new ar.edu.untdf.catalogo.jtablemodelo.CategoriaTableModel());
        tableCategorias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableCategorias.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(tableCategorias);

        jLabel2.setText("Nombre");

        nuevo.setText("Agregar");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        aceptar.setText("Guardar");
        aceptar.setEnabled(false);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.setEnabled(false);
        
        JButton btnEliminar = new JButton("Eliminar");
        btnEliminar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		   int fila = -1;
				if (fila  > -1){
        	            int codigo =  (int) (tableCategorias.getValueAt(fila, 0));            
        	            try {
        					cat.destroy(codigo);
        					tableCategorias.setModel(new CategoriaTableModel());

        				} catch (NonexistentEntityException e) {
        					// TODO Auto-generated catch block
        					e.printStackTrace();
        				}
        	            
        	            fila=-1;
        	        }
        	}
        });
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(20)
        			.addComponent(jLabel2)
        			.addGap(31)
        			.addComponent(fieldCuidad, GroupLayout.PREFERRED_SIZE, 206, GroupLayout.PREFERRED_SIZE)
        			.addGap(14)
        			.addComponent(nuevo, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(308)
        			.addComponent(aceptar, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(308)
        			.addComponent(cancelar, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(btnEliminar)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 393, GroupLayout.PREFERRED_SIZE)))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(24)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(4)
        					.addComponent(jLabel2))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(1)
        					.addComponent(fieldCuidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(nuevo))
        			.addGap(6)
        			.addComponent(aceptar)
        			.addGap(6)
        			.addComponent(cancelar)
        			.addGap(19)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 196, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(btnEliminar)
        			.addContainerGap(43, Short.MAX_VALUE))
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
    fieldCuidad.setText("");
    aceptar.setEnabled(true);
    cancelar.setEnabled(true);
    
    }//GEN-LAST:event_nuevoActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        Categoria c=new Categoria();
        c.setNombre(fieldCuidad.getText());
        
        CatalogoApp.getCategoriaC().create(c);
        tableCategorias.setModel(new CategoriaTableModel());
        aceptar.setEnabled(false);
        cancelar.setEnabled(false);
        
        
    }//GEN-LAST:event_aceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField fieldCuidad;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nuevo;
    private javax.swing.JTable tableCategorias;
}
