/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.edu.untdf.catalogo.views;

import ar.edu.untdf.catalogo.CatalogoApp;
import ar.edu.untdf.catalogo.controller.OrdenClienteJpaController;
import ar.edu.untdf.catalogo.controller.UsuarioJpaController;
import ar.edu.untdf.catalogo.jtablemodelo.OrdenClienteComboBoxModel;
import ar.edu.untdf.catalogo.jtablemodelo.OrdenClienteTableListener;
import ar.edu.untdf.catalogo.jtablemodelo.OrdenClienteTableModel;
import ar.edu.untdf.catalogo.modelo.Cliente;
import ar.edu.untdf.catalogo.modelo.OrdenCliente;
import ar.edu.untdf.catalogo.modelo.Usuario;


import javax.persistence.Persistence;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.border.TitledBorder;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import java.awt.Color;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;
/**
 *
 * @author Matias
 */
public class OrdenClientes extends javax.swing.JInternalFrame {

    
    private OrdenClienteJpaController ex = new OrdenClienteJpaController(Persistence.createEntityManagerFactory("catalogo"));		

    private static final long serialVersionUID = 1L;
	/**
     * Creates new form OrdenClientes
     */
    public OrdenClientes() {
		setForeground(Color.GREEN);
		setRootPaneCheckingEnabled(false);
		setBorder(new TitledBorder(null, "", TitledBorder.LEADING, TitledBorder.TOP, null, null));
		setSize(458,431);
		setTitle("Administracion de OrdenClientes");
		setClosable(true);
        initComponents();
        OrdenClienteTableListener listener = new OrdenClienteTableListener(this);
        tableOrdenClientes.getSelectionModel().addListSelectionListener(listener);
        
        
    }

    public JButton getAceptar() {
        return aceptar;
    }

    public void setAceptar(JButton aceptar) {
        this.aceptar = aceptar;
    }

    public JButton getCancelar() {
        return cancelar;
    }

    public void setCancelar(JButton cancelar) {
        this.cancelar = cancelar;
    }

    public JTable getTableOrdenClientes() {
        return tableOrdenClientes;
    }

    public void setTableOrdenClientes(JTable tableOrdenClientes) {
        this.tableOrdenClientes = tableOrdenClientes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrdenClientes = new javax.swing.JTable();
        nuevo = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();


        tableOrdenClientes.setModel(new ar.edu.untdf.catalogo.jtablemodelo.OrdenClienteTableModel());
        tableOrdenClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableOrdenClientes.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(tableOrdenClientes);

        nuevo.setText("Nueva Orden");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        aceptar.setText("Guardar");
        aceptar.setEnabled(false);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.setEnabled(false);
   

        JLabel lblUsuario = new JLabel("Usuario");
        
        JLabel lblCliente = new JLabel("Cliente");
        
        lblDireccion = new JLabel("Direccion");
        
        textFieldDireccion = new JTextField();
        textFieldDireccion.setColumns(10);
        
        JComboBox comboBoxCliente = new JComboBox();
        
        textFieldUsuario = new JTextField();
        textFieldUsuario.setColumns(10);
        
        JButton btnAgregarProducto = new JButton("Agregar Producto");
        
        JButton btnBorrarProducto = new JButton("Borrar Producto");
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
        			.addContainerGap(198, Short.MAX_VALUE)
        			.addComponent(btnAgregarProducto)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(btnBorrarProducto)
        			.addGap(72))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING, false)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(30)
        					.addComponent(lblDireccion)
        					.addGap(10)
        					.addComponent(textFieldDireccion, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(aceptar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        				.addGroup(Alignment.LEADING, groupLayout.createSequentialGroup()
        					.addGap(40)
        					.addComponent(lblCliente)
        					.addGap(10)
        					.addComponent(comboBoxCliente, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(nuevo, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE))
        				.addGroup(Alignment.LEADING, groupLayout.createSequentialGroup()
        					.addGap(37)
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addComponent(lblUsuario)
        							.addGap(10)
        							.addComponent(textFieldUsuario, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(cancelar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        			.addGap(27))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(11)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(lblCliente))
        				.addComponent(comboBoxCliente, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(nuevo))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(7)
        					.addComponent(lblDireccion))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(4)
        					.addComponent(textFieldDireccion, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE))
        				.addComponent(aceptar))
        			.addGap(11)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(4)
        					.addComponent(lblUsuario))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(1)
        					.addComponent(textFieldUsuario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addComponent(cancelar))
        			.addGap(18)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 236, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnAgregarProducto)
        				.addComponent(btnBorrarProducto)))
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
    aceptar.setEnabled(true);
    cancelar.setEnabled(true);
    
    }//GEN-LAST:event_nuevoActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        OrdenCliente c=new OrdenCliente();
        UsuarioJpaController u=new UsuarioJpaController(Persistence.createEntityManagerFactory("catalogo"));
        c.setCliente( (Cliente) comboBoxCliente.getSelectedItem());
        c.setDireccion(textFieldDireccion.getText());
        c.setUsuario((Usuario) (u.findUsuarioString(textFieldUsuario.getText())));
        CatalogoApp.getOrdenClienteC().create(c);
        tableOrdenClientes.setModel(new OrdenClienteTableModel());
        aceptar.setEnabled(false);
        cancelar.setEnabled(false);
        
        
    }//GEN-LAST:event_aceptarActionPerformed

    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nuevo;
    private javax.swing.JTable tableOrdenClientes;
    private JLabel lblDireccion;
    private JTextField textFieldDireccion;
    private JTextField textFieldUsuario;
    private JComboBox<Cliente> comboBoxCliente;
}
