/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.edu.untdf.catalogo.views;

import ar.edu.untdf.catalogo.CatalogoApp;
import ar.edu.untdf.catalogo.jtablemodelo.ProductoTableListener;
import ar.edu.untdf.catalogo.jtablemodelo.ProductoTableModel;
import ar.edu.untdf.catalogo.modelo.Producto;

import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.border.TitledBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JLabel;
import java.awt.Color;
import javax.swing.LayoutStyle.ComponentPlacement;

import com.mysql.jdbc.PreparedStatement;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.math.BigDecimal;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Matias
 */
public class Productos extends javax.swing.JInternalFrame {

    
	private static final long serialVersionUID = 1L;
	private File imagen ;
	/**
     * Creates new form Productos
     */
    public Productos() {
		setForeground(Color.GREEN);
		setRootPaneCheckingEnabled(false);
		setBorder(new TitledBorder(null, "", TitledBorder.LEADING, TitledBorder.TOP, null, null));
		setSize(458,448);
		setTitle("Administracion de Productos");
		setClosable(true);
        initComponents();
        ProductoTableListener listener = new ProductoTableListener(this);
        tableProductos.getSelectionModel().addListSelectionListener(listener);
        
        
    }

    public JButton getAceptar() {
        return aceptar;
    }

    public void setAceptar(JButton aceptar) {
        this.aceptar = aceptar;
    }

    public JButton getCancelar() {
        return cancelar;
    }

    public void setCancelar(JButton cancelar) {
        this.cancelar = cancelar;
    }

    public JTextField getFieldApellido() {
        return fieldPrecio;
    }

    public void setFieldApellido(JTextField fieldApellido) {
        this.fieldPrecio = fieldApellido;
    }


   
    public JTable getTableProductos() {
        return tableProductos;
    }

    public void setTableProductos(JTable tableProductos) {
        this.tableProductos = tableProductos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductos = new javax.swing.JTable();
        fieldPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setText("Precio");
        nuevo = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();


        tableProductos.setModel(new ar.edu.untdf.catalogo.jtablemodelo.ProductoTableModel());
        tableProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableProductos.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(tableProductos);

        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.setEnabled(false);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					aceptarActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        cancelar.setText("Cancelar");
        cancelar.setEnabled(false);
        
        JLabel lblFoto = new JLabel();
        lblFoto.setText("Foto");
        
        JLabel lblDescripcion = new JLabel();
        lblDescripcion.setText("Descripcion");
        
        fieldDescripcion = new JTextField();
        
        JButton btnNewButton = new JButton("Examinar");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de Imagen","jpg");
        		JFileChooser fileChooser = new JFileChooser();
        		fileChooser.setFileFilter(filter); 
        		fileChooser.setDialogTitle("Abrir archivo...");
        		File ruta = new File("C:/xampp/htdocs/catologo/imagenes");
        		fileChooser.setCurrentDirectory(ruta);
        		int result = fileChooser.showOpenDialog(null);
        		if (result == JFileChooser.APPROVE_OPTION)
        		{
        		File file = fileChooser.getSelectedFile();
        		imagen = file;
        		try {
        		FileInputStream fis = new FileInputStream(file);
        		} catch (FileNotFoundException ex) {
        		Logger.getLogger(Producto.class.getName()).log (Level.SEVERE, null, ex);
        		}
        		LblImg.setText("");
                ImageIcon icon = new ImageIcon( String.valueOf(file) );
        		LblImg.setIcon( icon );
        		}

        	}
        });
        
        LblImg = new JLabel("Foto del producto...");
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 422, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(15)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblDescripcion)
        				.addComponent(jLabel1)
        				.addComponent(lblFoto, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(LblImg, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addGroup(Alignment.LEADING, groupLayout.createParallelGroup(Alignment.LEADING, false)
        					.addComponent(fieldDescripcion)
        					.addComponent(fieldPrecio, GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
        				.addComponent(btnNewButton, Alignment.LEADING))
        			.addPreferredGap(ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(aceptar, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(nuevo, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        				.addComponent(cancelar, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE))
        			.addGap(25))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(17)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(fieldDescripcion, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblDescripcion)
        				.addComponent(nuevo))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(fieldPrecio, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1)
        				.addComponent(aceptar))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(cancelar)
        				.addComponent(lblFoto)
        				.addComponent(btnNewButton))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(LblImg, GroupLayout.PREFERRED_SIZE, 113, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 168, GroupLayout.PREFERRED_SIZE)
        			.addGap(2))
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected Icon ImageIcon(URL resource) {
		// TODO Auto-generated method stub
		return null;
	}

	private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
    fieldPrecio.setText("");
    aceptar.setEnabled(true);
    cancelar.setEnabled(true);
    
    }//GEN-LAST:event_nuevoActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_aceptarActionPerformed
        Producto c=new Producto();
        c.setDescripcion(fieldDescripcion.getText());
        c.setPrecio((BigDecimal.valueOf( (Long.parseLong(fieldPrecio.getText())))));
        FileInputStream fis = new FileInputStream(imagen);
        BufferedImage image = ImageIO.read(fis);

     
        ByteArrayOutputStream b = new ByteArrayOutputStream();
        ImageIO.write(image, "jpg", b);

        byte[] jpgByteArray = b.toByteArray();
		
        c.setFoto(jpgByteArray);
        CatalogoApp.getProductoC().create(c);
        tableProductos.setModel(new ProductoTableModel());
        aceptar.setEnabled(false);
        cancelar.setEnabled(false);
        
        
    }//GEN-LAST:event_aceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField fieldPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nuevo;
    private javax.swing.JTable tableProductos;
    private JTextField fieldDescripcion;
    private JLabel LblImg;
}
