/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.edu.untdf.catalogo.views;

import ar.edu.untdf.catalogo.CatalogoApp;
import ar.edu.untdf.catalogo.controller.TipoUsuarioJpaController;
import ar.edu.untdf.catalogo.jtablemodelo.TipoUsuarioComboBoxModel;
import ar.edu.untdf.catalogo.jtablemodelo.UsuarioTableListener;
import ar.edu.untdf.catalogo.jtablemodelo.UsuarioTableModel;

import ar.edu.untdf.catalogo.modelo.TipoUsuario;
import ar.edu.untdf.catalogo.modelo.Usuario;


import javax.persistence.Persistence;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.border.TitledBorder;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import java.awt.Color;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;
/**
 *
 * @author Matias
 */
public class Usuarios extends javax.swing.JInternalFrame {

    
    private TipoUsuarioJpaController ex = new TipoUsuarioJpaController(Persistence.createEntityManagerFactory("catalogo"));		

    private static final long serialVersionUID = 1L;
	/**
     * Creates new form Usuarios
     */
    public Usuarios() {
		setForeground(Color.GREEN);
		setRootPaneCheckingEnabled(false);
		setBorder(new TitledBorder(null, "", TitledBorder.LEADING, TitledBorder.TOP, null, null));
		setSize(458,448);
		setTitle("Administracion de Usuarios");
		setClosable(true);
        initComponents();
        UsuarioTableListener listener = new UsuarioTableListener(this);
        tableUsuarios.getSelectionModel().addListSelectionListener(listener);
        
        
    }

    public JButton getAceptar() {
        return aceptar;
    }

    public void setAceptar(JButton aceptar) {
        this.aceptar = aceptar;
    }

    public JButton getCancelar() {
        return cancelar;
    }

    public void setCancelar(JButton cancelar) {
        this.cancelar = cancelar;
    }

    public JTable getTableUsuarios() {
        return tableUsuarios;
    }

    public void setTableUsuarios(JTable tableUsuarios) {
        this.tableUsuarios = tableUsuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();
        nuevo = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        comboBoxTipoUsuario = new JComboBox<TipoUsuario>();


        tableUsuarios.setModel(new ar.edu.untdf.catalogo.jtablemodelo.UsuarioTableModel());
        tableUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableUsuarios.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(tableUsuarios);

        nuevo.setText("nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        aceptar.setText("aceptar");
        aceptar.setEnabled(false);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("cancelar");
        cancelar.setEnabled(false);
        
        comboBoxTipoUsuario.setModel(new TipoUsuarioComboBoxModel(ex));
        comboBoxTipoUsuario.setSelectedIndex(1);
   

        JLabel lblOrigen = new JLabel("TipoUsuario");
        
        JLabel lblDestino = new JLabel("Usuario");
        
        textFieldUsuario = new JTextField();
        textFieldUsuario.setColumns(10);
        
        lblPassword = new JLabel("Password");
        
        textFieldPassword = new JTextField();
        textFieldPassword.setColumns(10);
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addContainerGap(27, Short.MAX_VALUE)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(lblPassword)
        						.addComponent(lblDestino)
        						.addComponent(lblOrigen))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(comboBoxTipoUsuario, GroupLayout.PREFERRED_SIZE, 266, GroupLayout.PREFERRED_SIZE)
        						.addComponent(textFieldUsuario, GroupLayout.PREFERRED_SIZE, 262, GroupLayout.PREFERRED_SIZE)
        						.addComponent(textFieldPassword, GroupLayout.PREFERRED_SIZE, 263, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(cancelar, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        						.addComponent(nuevo, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)
        						.addComponent(aceptar, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE)))
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 422, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(30)
        			.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(nuevo)
        				.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(lblDestino)
        					.addComponent(textFieldUsuario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(11)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(aceptar)
        				.addComponent(lblPassword)
        				.addComponent(textFieldPassword, GroupLayout.PREFERRED_SIZE, 19, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(cancelar)
        				.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(lblOrigen)
        					.addComponent(comboBoxTipoUsuario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(21)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 236, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
    aceptar.setEnabled(true);
    cancelar.setEnabled(true);
    
    }//GEN-LAST:event_nuevoActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        Usuario c=new Usuario();
        c.setUsuario(textFieldUsuario.getText());
        c.setPassword(textFieldPassword.getText());
        c.setTipoUsuario((TipoUsuario) comboBoxTipoUsuario.getSelectedItem());
        CatalogoApp.getUsuarioC().create(c);
        tableUsuarios.setModel(new UsuarioTableModel());
        aceptar.setEnabled(false);
        cancelar.setEnabled(false);
        
        
    }//GEN-LAST:event_aceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nuevo;
    private javax.swing.JTable tableUsuarios;
    private javax.swing.JComboBox<TipoUsuario> comboBoxTipoUsuario;
    private JTextField textFieldUsuario;
    private JLabel lblPassword;
    private JTextField textFieldPassword;

}
